#!/bin/bash
echo '-----------------------------'
g++ -Wall -I/usr/include/cppconn storage.cpp -L/usr/lib -lmysqlcppconn
echo '-----------------------------'
if [ "x$?" == "x0" ]
then
echo -e "DATABASE SELECT * FROM lel\nDATABASE SELECT * FROM lel\nEND" | ./a.out
echo -e "FILE TAKE penis" | ./a.out
else
echo 'compile error'
fi
echo '-----------------------------'
