#!/bin/bash
echo '-----------------------------'
g++ -Wall -I/usr/include/cppconn storaged.cpp -o storaged -L/usr/lib -lmysqlcppconn
chmod +x storaged
echo '-----------------------------'
if [ "x$?" == "x0" ]
then
echo -e "DATABASE SELECT * FROM lel\nDATABASE SELECT * FROM lel\nEND" | ./storaged
echo -e "FILE TAKE penis" | ./storaged
else
echo 'compile error'
fi
echo '-----------------------------'
